parameters:
#    stcw_formation.example.class: Stcw\FormationBundle\Example

services:
#    stcw_formation.example:
#        class: %stcw_formation.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
