parameters:
#    stcw_desk.example.class: Stcw\DeskBundle\Example

services:
#    stcw_desk.example:
#        class: %stcw_desk.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
