<?php

namespace Stcw\FormationBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CourseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CourseRepository extends EntityRepository
{
    public function findallOrdered()
    {
        $query = $this->createQueryBuilder('c')
                //->orderBy('c.modules')
                ->orderBy('c.code')
                ->getQuery();
        
        return $query->getResult();
    }
}