<?php

namespace Stcw\FormationBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ModuleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ModuleRepository extends EntityRepository
{
        public function listOrder()
    {
        $query = $this->createQueryBuilder('m')
                ->orderBy('m.level')
                ->getQuery();
        
        return $query->getResult();
    }
    
    public function showModule($id)
    {
        $query = $this->createQueryBuilder('m')
                ->where('m.id = :id')
                ->addSelect('c')
                ->leftJoin('m.courses', 'c')
                ->setParameter('id', $id)
                ->getQuery();
        
        return $query->getSingleResult();
    }
}