<?php

namespace Stcw\ResultBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ResultReportRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ResultReportRepository extends EntityRepository
{
}