parameters:
#    stcw_school.example.class: Stcw\SchoolBundle\Example

services:
#    stcw_school.example:
#        class: %stcw_school.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
