parameters:
#    stcw_certificate.example.class: Stcw\CertificateBundle\Example

services:
#    stcw_certificate.example:
#        class: %stcw_certificate.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
