parameters:
#    stcw_student.example.class: Stcw\StudentBundle\Example

services:
#    stcw_student.example:
#        class: %stcw_student.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
