<?php

namespace Stcw\StudentBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryRepository extends EntityRepository
{
    public function findRelated($id)
    {
        $query = $this->createQueryBuilder('c')
                ->addSelect('m')
                ->leftJoin('c.modules', 'm')
                ->where('c.id = :id')
                ->orderBy('m.level')
                ->setParameter('id', $id)
                ->getQuery();
        
        return $query->getSingleResult();
    }
}