<?php

namespace Stcw\StudentBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ClasseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClasseRepository extends EntityRepository
{
    public function show($id)
    {
        $query = $this->createQueryBuilder('c')
                ->addSelect('s')
                ->addSelect('p')
                ->leftJoin('c.students', 's')
                ->leftJoin('s.profile', 'p')
                ->where('c.id = :id')
                ->setParameter('id', $id)
                ->getQuery();
        
        return $query->getSingleResult();
    }
    
    public function listAllTest()
    {
        $query = $this->createQueryBuilder('c');
          $query->addSelect('COUNT(c) AS total')
                ->addSelect('y')
                ->leftJoin('c.school', 'y')
                ->leftJoin('c.students','s', \Doctrine\ORM\Query\Expr\Join::WITH, 'c.id  = s.classe')
                ->groupBy('c.id')
                ->orderBy('y.id')            
                ->addOrderBy('c.title');
                //->getQuery();
        echo '<pre>';
        print_r($query->getDQL());
        print_r($query->getQuery()->getArrayResult());
        exit();
        return $query->getQuery()->getResult();
    }
    
    public function listAll()
    {
        $query = $this->createQueryBuilder('c');
                $query
                ->addSelect('y')
                ->addSelect('s')
                ->leftJoin('c.students', 'y')
                ->leftJoin('c.school', 's')
                ->orderBy('s.id')
                ->addOrderBy('c.title');
                        
        return $query->getQuery()->getResult();
    }
    
    public function findByRelated($id)
    {
        $query = $this->createQueryBuilder('c')
                ->addSelect('s')
                ->leftJoin('c.students', 's')
                ->where('c.id = :id')
                ->orderBy('s.lastname')
                ->setParameter('id', $id)
                ->getQuery();

        return $query->getSingleResult();
    }
    
}