<?php

namespace Stcw\StudentBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * StudentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StudentRepository extends EntityRepository
{

    public function findRelated($id)
    {
        $em = $this->getEntityManager();
        $query = $this->createQueryBuilder('s')
                ->addSelect('p')
                ->addSelect('q')
                ->where('s.id = :id')
                ->join('s.profile', 'p')
                ->join('s.promotion', 'q')
                ->setParameter('id', $id)
                ->getQuery();

        return $query->getSingleResult();
    }

    public function findAllSort()
    {
        $query = $this->createQueryBuilder('s')
                ->addSelect('p')
                ->addSelect('c')
                ->addSelect('q')
                ->addSelect('r')
                ->join('s.profile', 'p')
                ->leftJoin('s.promotion', 'q')
                ->leftJoin('s.category', 'c')
                ->leftJoin('s.classe', 'r')
                ->orderBy('s.lastname')
                ->getQuery();

        return $query->getResult();
    }

    public function findRelatedFor($id)
    {
        $em = $this->getEntityManager();
        $query = $em->createQuery('
            SELECT s, p FROM StcwStudentBundle:Student s
            JOIN s.profile p
            WHERE s.id = :id')
                ->setParameter('id', $id);

        return $query->getSingleResult();
    }
}